spring:

  datasource:
    postgres:
      # data source properties
      jdbc-url: jdbc:postgresql://localhost:5432/local
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres

      hibernate:
        # for query syntax ( query translation )
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
        # auto: validate
          auto: update
      # jpa properties
      jpa:
        show-sql: false
        properties:
          hibernate:
            ddl-auto: update
            format_sql: true
            use_sql_comments: true

    hsqldb:
      # data source properties
      jdbc-url: jdbc:hsqldb:hsql://localhost:9001/hsql
      driver-class-name: org.hsqldb.jdbc.JDBCDriver
      username: hsql
      password: hsql

      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        hbm2ddl:
          # auto: validate
          auto: validate

      # jpa properties
      jpa:
        show-sql: true
        properties:
          hibernate:
            ddl-auto: update
            format_sql: false
            use_sql_comments: true




  # Logging levels
logging.level:
    org.hibernate.SQL: OFF # DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE