project-management-app:
  someKey: someValue
  jwt:
    issuer: self
    publicKey: classpath:public.key
    privateKey: classpath:private.key
    expiration: 3600


spring:
  application:
    name: project-management-app

  datasource:
    url: jdbc:h2:file:/home/ravinder/Drive/work-spaces/java/intellij-projects/spring-boot-learn/learn8-security/jwt/jwt7-project-management/src/main/resources/data.db
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false # keeps hibernate session active for entire request
                        # instead of only method execution
                        # disable this & handle lazy loading data from DBs
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: true
    locations: classpath:db/migrations



logging:
  level:
    com.paravar: DEBUG