version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - elk-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - elk-network

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.15.0
    ports:
      - "8200:8200"
    volumes:
      - ./apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml
    depends_on:
      - elasticsearch
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    volumes:
      - kibana-data:/usr/share/kibana/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 10s
      timeout: 5s
      retries: 6
    networks:
      - elk-network

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.15.0
    user: root
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - ./metricbeat/modules.d:/usr/share/metricbeat/modules.d
    depends_on:
      elasticsearch:
        condition: service_started
      kibana:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: metricbeat -e -strict.perms=false
    networks:
      - elk-network

volumes:
  elasticsearch-data:
  kibana-data:

networks:
  elk-network:
    driver: bridge